### ISSUE TITLE
cant compile this

### ISSUE THREAD

**Issue by r3k2** [kmahyyg/mremoteng-decrypt#3]
I am a go/ruby/C person Im trying to use javac to compile this as if I will compile a C program
but even do I installed the dependencies with de arch linux AUR  it keeps missing them... not a java person I download the dependencies and put them on the same directory and still not picking them up...

**Comment by r3k2** [comment]
ok I read some docs and got this:
```
javac -cp '../../../../lib/*' Main.java
```
that created a .class ????

**Comment by r3k2** [comment]
ok nevermind I read some more and got the .jar etc.

**Comment by r3k2** [comment]
for anyone else not familiar with java but with other diff languages I notice he used intellij IDE so downloaded it that only created also a .class so I search in how to create a jar from the IDE 
https://www.youtube.com/watch?v=3Xo6zSBgdgk&t=16s
then it all worked fine and used the resulting jar to decrypt.
good luck.

**Comment by kmahyyg** [comment]
why not use Python one?

**Comment by kmahyyg** [comment]
You need to install the dependencies in readme and I didn't use maven to manage them due to that will make the project bigger.

Also, the java source code is used for reviewing and I will never answer any compiling related questions cuz there's a Python version here (which is much more efficient and convenient).

So sorry for any inconvenience I caused.

**Comment by kmahyyg** [comment]
Also as an Arch user,  I suggest u only install Oracle JDK 8 from AUR, other dependencies should be downloaded from Maven central repository.

Thanks for your understanding. Currently I am so busy to working on FOSS.
